[versions]
springBoot = "3.4.1"
java = "21"
h2 = "2.2.224"
postgresql = "42.7.3"
lombok = "1.18.32"

[libraries]
# Plataforma (BOM)
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot" }

# Starters
starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }

# Base de Datos
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }

# Herramientas
java-lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# Testing
starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
